[Spring-boot-practice] add category
Andriy-Hrynevetskyi/spring-boot-book-store pull request #10
Opened 2023-12-28 15:19 UTC by Andriy-Hrynevetskyi

Adds a category entity and ability to search books by it

2023-12-28 19:25 UTC, annton-shakur approved these changes
Good job! i left a few minor points to consider

2023-12-28 19:25 UTC, annton-shakur commented on src/main/java/bookstore/mapper/BookMapper.java
> +        if (book.getCategories() != null) {
It's never really null, as we have initialized it like that: Set<Category> categories = new HashSet<>();
you may use !book.getCategories().isEmpty() instead

2023-12-28 19:25 UTC, annton-shakur commented on src/main/java/bookstore/service/category/CategoryServiceImpl.java
> +                () -> new EntityNotFoundException("Can't find a category with given id: " + id));
maybe a constant for the message would nice (it's used twice as i see)

2023-12-28 19:25 UTC, annton-shakur commented on src/main/resources/application.properties
> +spring.datasource.password=07121990@Vg
if it's your actual password, you better change it

2023-12-28 19:25 UTC, annton-shakur commented on src/main/resources/db/changelog/changes/09-create-books-categories-table.yaml
> +              columnNames: book_id, category_id
pls make sure to have an empty line at the end of file

2023-12-28 19:25 UTC, annton-shakur commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/09-create-books-categories-table.yaml
pls make sure to have an empty line at the end of file

2023-12-29 07:45 UTC, d1sam requested changes
good job, but some changes should be done!

2023-12-29 07:45 UTC, d1sam commented on src/main/java/bookstore/controller/CategoryController.java
> +    @PostMapping()
```suggestion
    @PostMapping
```

2023-12-29 07:45 UTC, d1sam commented on src/main/java/bookstore/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasRole('ROLE_ADMIN')")
    @ResponseStatus(HttpStatus.CREATED)
```

2023-12-29 07:45 UTC, d1sam commented on src/main/java/bookstore/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
```suggestion
    @ResponseStatus(value = HttpStatus.NO_CONTENT)
    @PreAuthorize("hasRole('ROLE_ADMIN')")
```

2023-12-29 07:45 UTC, d1sam commented on src/main/java/bookstore/dto/book/BookWithoutCategoryIds.java
> +public class BookWithoutCategoryIds {
```suggestion
@Data
public class BookWithoutCategoryIds {
```

2023-12-29 07:45 UTC, d1sam commented on src/main/java/bookstore/dto/category/CategoryDto.java
> +public class CategoryDto {
```suggestion
@Data
public class CategoryDto {
```

2023-12-29 07:45 UTC, d1sam commented on src/main/java/bookstore/dto/category/CategoryRequestDto.java
> +public class CategoryRequestDto {
```suggestion
@Data
public class CategoryRequestDto {
```

2023-12-29 07:45 UTC, d1sam commented on src/main/java/bookstore/model/Book.java
> +    private Set<Category> categories = new HashSet<>();
exclude from `equals/hashCode` and `toString`.

2023-12-29 07:45 UTC, d1sam commented on src/main/java/bookstore/model/Category.java
> +    private String description;
```suggestion
    @Column
    private String description;
```

2023-12-29 07:45 UTC, d1sam commented on src/main/java/bookstore/model/Category.java
> +@Data
```suggestion
@Data
@NoArgsConstructor
```

2023-12-29 07:45 UTC, d1sam commented on src/main/java/bookstore/repository/book/BookRepository.java
>  public interface BookRepository extends JpaRepository<Book, Long> {
```suggestion
@Repository
public interface BookRepository extends JpaRepository<Book, Long> {
```

2023-12-29 07:45 UTC, d1sam commented on src/main/resources/db/changelog/changes/05-insert-roles.yaml
> +
```suggestion
```

2023-12-29 07:45 UTC, d1sam commented on src/main/resources/db/changelog/changes/06-insert-users.yaml
> +
```suggestion
```

2023-12-29 07:45 UTC, d1sam commented on src/main/resources/db/changelog/changes/08-create-categories-table.yaml
> +                    nullable: false
```suggestion
```
it's unnecessary, because you have `primary key`

2023-12-29 07:45 UTC, d1sam commented on src/main/resources/db/changelog/changes/09-create-books-categories-table.yaml
> +                    nullable: false
```suggestion
```
it's unnecessary, because you have `primary key`

2023-12-29 07:45 UTC, d1sam commented on src/main/resources/db/changelog/changes/09-create-books-categories-table.yaml
> +                    nullable: false
```suggestion
```
it's unnecessary, because you have `primary key`

2023-12-29 11:43 UTC, vovasalyha approved these changes
Approving, but please write meaningful commit message with the changes you made. Commit message `added improvements after code review` is very uninformative.

2023-12-31 13:51 UTC, merged