[hw-spring-boot-data-jpa] implemented update and delete logic
Andriy-Hrynevetskyi/spring-boot-book-store pull request #2
Opened 2023-12-08 16:22 UTC by Andriy-Hrynevetskyi

2023-12-08 18:03 UTC, MinoDentori approved these changes
Good job! Just one small moment to proceed.

2023-12-08 18:03 UTC, MinoDentori commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
Add a new line to the end of the file)

<img width="623" alt="Screenshot 2023-12-08 at 20 01 23" src="https://github.com/Andriy-Hrynevetskyi/spring-boot-book-store/assets/45499568/afbc7e7b-eb78-4a73-a85b-550a9e6b6959">

2023-12-08 18:04 UTC, Andriy-Hrynevetskyi commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
ok ty)

2023-12-11 10:09 UTC, d1sam requested changes
Good job, but some changes should be done!

2023-12-11 10:09 UTC, d1sam commented on src/main/java/bookstore/controller/BookController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
```suggestion
```

2023-12-11 10:09 UTC, d1sam commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +      author: andriy
you should also write your lastname

2023-12-11 10:50 UTC, d1sam approved these changes
Well done!

2023-12-11 12:33 UTC, merged