[spring-boot-hw-bookstore] added spring boot security
Andriy-Hrynevetskyi/spring-boot-book-store pull request #7
Opened 2023-12-22 17:39 UTC by Andriy-Hrynevetskyi

list 0f changes:
- spring security starter
-SecurityConfig
-implemented role access
-added role entitty and all neccessary services dto repositories...
- implemented CustomUserDetailsService 
- added liquibase scripts

2023-12-22 22:11 UTC, HovorukhaBohdan approved these changes
Good job!

2023-12-26 08:45 UTC, d1sam requested changes
Good job, but some changes should be done according to my comment

2023-12-26 08:45 UTC, d1sam commented on src/main/java/bookstore/config/SecurityConfig.java
> +                        auth -> auth.requestMatchers("/auth/**","/error","/swagger-ui/**")
```suggestion
                        auth -> auth.requestMatchers("/auth/**","/error","/swagger-ui/**", "/v3/api-docs/**")
```

2023-12-26 08:45 UTC, d1sam commented on src/main/java/bookstore/model/User.java
> +        return true;
```suggestion
        return !deleted;
```

2023-12-26 08:45 UTC, d1sam commented on src/main/java/bookstore/model/User.java
> +        return true;
```suggestion
        return !deleted;
```

2023-12-26 08:45 UTC, d1sam commented on src/main/java/bookstore/model/User.java
> +        return true;
```suggestion
        return !deleted;
```

2023-12-26 08:45 UTC, d1sam commented on src/main/java/bookstore/model/User.java
> +        return true;
```suggestion
        return !deleted;
```

2023-12-26 08:45 UTC, d1sam commented on src/main/java/bookstore/model/User.java
> +
```suggestion
  @Column(nullable = false)
  private boolean deleted = false;
```

2023-12-26 08:45 UTC, d1sam commented on src/main/java/bookstore/model/User.java
>  @Data
```suggestion
@Data
@SQLDelete(sql = "UPDATE users SET deleted = true WHERE id=?")
@Where(clause = "deleted=false")
```

2023-12-26 08:45 UTC, d1sam commented on src/main/java/bookstore/repository/role/RoleRepository.java
> +public interface RoleRepository extends JpaRepository<Role, Long> {
```suggestion
@Repository
public interface RoleRepository extends JpaRepository<Role, Long> {
```

2023-12-26 08:45 UTC, d1sam commented on src/main/java/bookstore/service/user/UserServiceImpl.java
> +        user.setShippingAddress(requestDto.getShippingAddress());
use mapper

2023-12-26 08:45 UTC, d1sam commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
> +                    references: roles(id)
add empty line to the end of file

2023-12-26 08:45 UTC, d1sam commented on src/main/resources/db/changelog/changes/05-add-role-id-column-to-users-table.yaml
why do you need this column? you have `users_roles` table

2023-12-26 08:45 UTC, d1sam commented on src/main/resources/db/changelog/changes/06-insert-users.yaml
you should add roles to users by users_roles table and use valueComputed

2023-12-27 07:50 UTC, d1sam requested changes
Good job, but please add composite key to `users_roles` table on columns `user_id` and `role_id`

2023-12-27 07:50 UTC, d1sam commented on src/main/resources/db/changelog/changes/07-insert-values-in-users-roles-table.yaml
> +                  valueComputed: (SELECT id FROM roles WHERE role='USER')
please add empty line at the end of file

2023-12-27 07:50 UTC, d1sam commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
`users_roles` table should have composite key on columns: `user_id` and `role_id`.

2023-12-27 08:19 UTC, d1sam approved these changes

2023-12-27 08:19 UTC, d1sam commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
well done, but please pay attention to the empty line at the end of file :)

2023-12-27 16:59 UTC, merged