[Hw-spring-boot-jwt-token] implemented login feature via jwt token
Andriy-Hrynevetskyi/spring-boot-book-store pull request #9
Opened 2023-12-25 17:44 UTC by Andriy-Hrynevetskyi

2023-12-26 13:16 UTC, andrii-hoienko requested changes

2023-12-26 13:16 UTC, andrii-hoienko commented on src/main/java/bookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please make "Bearer " constant

2023-12-26 13:16 UTC, andrii-hoienko commented on src/main/java/bookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
magic number

2023-12-27 10:34 UTC, d1sam approved these changes
Well done :)

2023-12-27 17:00 UTC, merged